font:
  - file: "gfonts://Roboto"
    id: roboto17_font
    size: 17
    bpp: 4
    glyphsets: [GF_Latin_Core]
    glyphs: "°äöüÄÖÜß€" # Explizit als Glyphen hinzufügen

  - file: "gfonts://Roboto"
    id: roboto15_font
    size: 15
    bpp: 4
    glyphsets: [GF_Latin_Core]
    glyphs: "°€"  # Explizit als Glyphen hinzufügen

  - file: "gfonts://Roboto"
    id: font_roboto_56 # Für die große Uhrzeit/Datumsanzeige
    size: 56
    bpp: 4
    # Das Leerzeichen am Ende wurde entfernt.
    # GF_Latin_Core (standardmäßig für gfonts geladen) enthält bereits das Leerzeichen.
    # Die Buchstaben Aa-Zz und Umlaute sind hier wichtig für Wochentage/Monate.
    glyphs: "0123456789.:,AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzäöüÄÖÜß"

  - file: "gfonts://Roboto"
    id: font_roboto_28 # Für Wetterbeschreibung und Temperaturwerte
    size: 28
    bpp: 4
    # GF_Latin_Extended_A deckt viele europäische Zeichen inkl. Umlaute ab.
    # Grad und Euro explizit, falls nicht in Extended_A enthalten.
    glyphsets: [GF_Latin_Core, GF_Latin_Extended_A]
    glyphs: "°€"

substitutions:
  font_time_date: font_roboto_56
  font_weather_text: font_roboto_28
  text_font: roboto17_font

lvgl:
  style_definitions:
    - id: roboto15_style
      text_font: roboto15_font
