font:
  - file: "gfonts://Roboto"
    id: roboto17_font
    size: 17
    bpp: 4
    glyphsets: [GF_Latin_Core, GF_Currency, "°äöüÄÖÜß"] # Grundlegend + Währung + Grad + Umlaute

  - file: "gfonts://Roboto"
    id: roboto15_font
    size: 15
    bpp: 4
    glyphsets: [GF_Latin_Core, GF_Currency, "°"] # Grundlegend + Währung + Grad

  - file: "gfonts://Roboto"
    id: font_roboto_56 # Für die große Uhrzeit/Datumsanzeige
    size: 56
    bpp: 4
    # Benötigte Zeichen für Zeit/Datum: Zahlen, Doppelpunkt, Punkt, Komma, Leerzeichen
    # und Buchstaben für Wochentage und Monatsnamen.
    # GF_Latin_Core enthält die meisten Buchstaben und Zahlen.
    # Füge spezifische Zeichen hinzu, die für formatierte Daten benötigt werden.
    glyphs: "0123456789.:, AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZzäöüÄÖÜß "

  - file: "gfonts://Roboto"
    id: font_roboto_28 # Für Wetterbeschreibung und Temperaturwerte
    size: 28
    bpp: 4
    # Benötigt Buchstaben (inkl. Umlaute), Zahlen, Satzzeichen, Gradzeichen.
    glyphsets: [GF_Latin_Core, GF_Latin_Extended_A, GF_Currency, "°"]

substitutions:
  font_time_date: font_roboto_56
  font_weather_text: font_roboto_28
  text_font: roboto17_font # Wird von button.yaml verwendet

lvgl:
  style_definitions:
    - id: roboto15_style
      text_font: roboto15_font
