# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 36
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F042B",  # mdi-printer-3d
      "\U000F0D43",  # mdi-air-filter
      "\U000F1051",  # mdi-led-strip-variant
      "\U000F03D7",  # mdi-package-variant-closed
      "\U000F07D6",  # mdi-led-strip
      "\U000F1A6C",  # mdi-blinds-closed
      "\U000F1A6B",  # mdi-blinds-open
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F1087",  # mdi-router-network
      "\U000F036B",  # mdi-message-video
      "\U000F0614",  # mdi-application-outline
      "\U000F07C9",  # mdi-forklift
      "\U000F02AB",  # mdi-gmail
      "\U000F04B1",  # mdi-slack
      "\U000F0633",  # mdi-command
      "\U000F050F",  # mdi-thermometer
      "\U000F10C3",  # mdi-thermometer-low
      "\U000F10C2",  # mdi-thermometer-high
      "\U000F192D",  # mdi-grid-import
      "\U000F02D1",  # mdi-heart
      "\U000F05F1",  # mdi-ev-station
      "\U000F140B",  # mdi-lightning-bolt
      "\U000F0425",  # mdi-power
      "\U000F068A",  # mdi-shield-home
      "\U000F02DC",  # mdi-home
      "\U000F1A91",  # mdi-cash-clock
      "\U000F0F54",  # mdi-home-thermometer
      "\U000F18D6",  # mdi-sun-thermometer
      "\U000F1818",  # mdi-bathtub
      "\U000F1A43",  # mdi-heat-pump
      "\U000F0336",  # mdi-lightbulb-off
      "\U000F0FA6",  # mdi-car-seat-heater
      "\U000F1054",  # mdi-outdoor-lamp
      "\U000F1A85",  # mdi-water-thermometer
      "\U000F058E",  # mdi-water-percent
      "\U000F1A45",  # mdi-heat-wave
      "\U000F0E02",  # mdi-thermometer-chevron-down
      "\U000F0DA1",  # mdi-transfer-down
      "\U000F0E03",  # mdi-thermometer-chevron-up
      "\U000F0DA3",  # mdi-transfer-up
      "\U000F0F9C",  # mdi-home-import-outline
      "\U000F0F9B",  # mdi-home-export-outline
      "\U000F0510",  # mdi-thermometer-lines
      "\U000F1402",  # mdi-pump
      "\U000F0731",  # mdi:arrow-left
      "\U000F0734",  # mdi-arrow-right
      "\U000F05AA",  # mdi-wifi-off
      "\U000F091B",  # mdi-wifi-strength-outline
      "\U000F091C",  # mdi-wifi-strength-1
      "\U000F091D",  # mdi-wifi-strength-2
      "\U000F091E",  # mdi-wifi-strength-3
      "\U000F091F",  # mdi-wifi-strength-4
      "\U000F17C7",  # mdi-ceiling-light-outline
      "\U000F0769",  # mdi-ceiling-light
      "\U000F17C8",  # mdi:floor-lamp-outline
      "\U000F08DD",  # mdi:floor-lamp
      "\U000F1041",  # mdi:floor-lamp-torchiere-variant
      "\U000F17CF",  # mdi:floor-lamp-torchiere-variant-outline
      "\U000F18DE",  # mdi:ceiling-light-multiple-outline
      "\U000F18DD",  # mdi:ceiling-light-multiple
      
      
    ]

  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font_header
    size: 15
    bpp: 4
    glyphs: [
      "\U000F050F",  # thermometer
      "\U000F092E",  # mdi-wifi-strength-off-outline
      "\U000F091B",  # mdi-wifi-strength-outline
      "\U000F091C",  # mdi-wifi-strength-1
      "\U000F091D",  # mdi-wifi-strength-2
      "\U000F091E",  # mdi-wifi-strength-3
      "\U000F091F",  # mdi-wifi-strength-4
      "\U000F0731",  # mdi-arrow-left-bold
      "\U000F0734",  # mdi-arrow-right-bold
      "\U000F02DC",  # mdi-home
      ]

# Map icons to names
substitutions:
  lightbulb:           "\U000F0335"
  printer:             "\U000F042B"
  aircon:              "\U000F0D43"
  ledstrip:            "\U000F1051"
  package:             "\U000F03D7"
  lights:              "\U000F07D6"
  blinds_closed:       "\U000F1A6C"
  blinds_open:         "\U000F1A6B"
  nightlight:          "\U000F1A4C"
  network:             "\U000F1087"
  videocall:           "\U000F036B"
  application:         "\U000F0614"
  forklift:            "\U000F07C9"
  gmail:               "\U000F02AB"
  slack:               "\U000F04B1"
  command:             "\U000F0633"
  thermometer:         "\U000F050F"
  thermometer_low:     "\U000F10C3"
  thermometer_high:    "\U000F10C2"
  grid_import:         "\U000F192D"
  heart:               "\U000F02D1"
  ev_station:          "\U000F05F1"
  lightning_bolt:      "\U000F140B"
  power:               "\U000F0425"
  shield_home:         "\U000F068A"
  home:                "\U000F02DC"
  cash_clock:          "\U000F1A91"
  home_thermometer:    "\U000F0F54"
  sun_thermometer:     "\U000F18D6"
  bathtub:             "\U000F1818"
  heat_pump:           "\U000F1A43"
  lightbulb_off:       "\U000F0336"
  car_seat_heater:     "\U000F0FA6"
  outdoor_lamp:        "\U000F1054"
  water_thermometer:   "\U000F1A85"
  water_percent:       "\U000F058E"
  heat_wave:           "\U000F1A45"
  thermometer_chevron_down: "\U000F0E02"
  transfer_down:       "\U000F0DA1"
  thermometer_chevron_up:   "\U000F0E03"
  transfer_up:         "\U000F0DA3"
  home_import_outline: "\U000F0F9C"
  home_export_outline: "\U000F0F9B"
  thermometer_lines:   "\U000F0510"
  pump:                "\U000F1402"
  arrow_left:          "\U000F0731"
  arrow_right:         "\U000F0734"
  ceiling_off:         "\U000F17C7"
  ceiling_on:          "\U000F0769"
  floor_lamp_off:      "\U000F17C8"
  floor_lamp_on:       "\U000F08DD"
  floor_lamp_variant_on:  "\U000F1041"
  floor_lamp_variant_off:  "\U000F17CF"
  ceiling_group_off:    "\U000F18DE"
  ceiling_group_on:     "\U000F18DD"
