# Materialdesign Weather Icons for main page
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_100
    size: 100
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      "\U000F050F"  # thermometer
       "\U000F0596", # mdi-weather-pouring
      "\U000F0598", # mdi-weather-snowy
      "\U000F0F33", # mdi-weather-fog (Alternative zu \U000F0591)
      "\U000F059C", # mdi-weather-windy
      "\U000F059A", # mdi-weather-sunset
      "\U000F059B", # mdi-weather-sunset-down
      "\U000F059C", # mdi-weather-sunset-up (Tippfehler im MDI-Namen, es ist windy)
      "\U000F059E", # mdi-weather-windy-variant
    ]

substitutions:
  font_weather_main_icon: icon_100
