substitutions:
  icon_font: icon_font
  text_font: roboto17_font
  button_on_color: "0xFF8C00"
  button_text_color: "0xFFFFFF"
  button_control_color: "0x313131"
  button_webhook_color: "0x212121"
  button_height_single: 102px
  button_height_double: 216px
  button_width: 149px
  padding: 8px
  radius: 12px
  slider_background_color: "0x505050"
  slider_active_color: "0x2D2D2D"
  slider_knob_color: "0xE5E5E5"
  arrow_left_icon:  "\U000F073A"  # Geändert zu mdi-arrow-left-bold
  home_icon:        "\U000F02DC"  # Bleibt mdi-home
  arrow_right_icon: "\U000F073B" # Geändert zu mdi-arrow-right-bold

lvgl:
  style_definitions:
    - id: webhook
      bg_color: $button_webhook_color
    - id: control
      bg_color: $button_control_color

  theme:
    button:
      text_font: $text_font
      scroll_on_focus: false
      radius: $radius
      width: $button_width
      height: $button_height_single
      pad_all: $padding
      shadow_width: 0
      text_color: $button_text_color
      bg_color: $button_control_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
