# Designed for Waveshare ESP32-S3-Touch-LCD-7
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB

framework:
  type: esp-idf
  sdkconfig_options:
    COMPILER_OPTIMIZATION_SIZE: y
    CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
    CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
    CONFIG_FREERTOS_HZ: "1000"
    CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_160: y
    CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: n
    CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
    CONFIG_ESPTOOLPY_FLASHFREQ_80M: y
    CONFIG_ESPTOOLPY_FLASHFREQ_120M: n
    CONFIG_SPIRAM_MODE_OCT: y
    CONFIG_IDF_EXPERIMENTAL_FEATURES: y
    CONFIG_SPIRAM_SPEED_80M: y
    CONFIG_SPIRAM_SPEED_120M: n
    CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
    CONFIG_SPIRAM_RODATA: y
    CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
    CONFIG_COMPILER_OPTIMIZATION_PERF: y

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

ota:
  platform: ESPHome

api:

logger:

psram:
  mode: octal
  speed: 80MHz

ch422g:
  - id: ch422g_hub

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: True
  id: bus_a

touchscreen:
  platform: gt911
  id: my_touch
  interrupt_pin: GPIO4
  reset_pin:
    ch422g: ch422g_hub
    number: 1
    mode: OUTPUT
  on_touch:
    - lambda: |-
        ESP_LOGI("Touch", "Touch detected at x=%d, y=%d", touch.x, touch.y);
  on_update:
    - lambda: |-
        for (auto touch: touches) {
          if (touch.state <= 2) {
            ESP_LOGI("Touch points:", "id=%d x=%d, y=%d x.raw=%d, y.raw=%d", touch.id, touch.x, touch.y, touch.x_raw, touch.y_raw);
          }
        }
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:

display:
  - platform: rpi_dpi_rgb
    id: my_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 16MHZ
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    reset_pin:
      ch422g: ch422g_hub
      number: 3
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1
        - 2
        - 42
        - 41
        - 40
      blue:
        - 14
        - 38
        - 18
        - 17
        - 10
      green:
        - 39
        - 0
        - 45
        - 48
        - 47
        - 21
