# backlight.yaml
substitutions:
  friendly_name:
  backlight_brightness_pin: "GPIO16" 
  initial_brightness_on_pres: "1.0" 
  initial_brightness_on_boot: "0.8" 

output:
  - platform: ledc
    pin: ${backlight_brightness_pin}
    id: lcd_backlight_pwm
    frequency: 1000 Hz

light:
  - platform: monochromatic
    name: "${friendly_name} Backlight"
    id: lcd_backlight_brightness
    output: lcd_backlight_pwm
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    gamma_correct: 0

esphome:
  on_boot:
    priority: -10.0
    then:
      - light.turn_on:
          id: lcd_backlight_brightness
          brightness: !lambda 'return ${initial_brightness_on_boot};'

binary_sensor:
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.wz_presence
    on_press:
      - lvgl.resume:
      - delay: 10ms
      - light.turn_on:
          id: lcd_backlight_brightness
          brightness: !lambda 'return ${initial_brightness_on_pres};'
      - logger.log: "Screensaver is turned off, backlight ON"
    on_release:
      - light.turn_off:
          id: lcd_backlight_brightness
      - lvgl.pause:
          show_snow: true
      - logger.log: "Screensaver is turned on, backlight OFF"
