# wz-display.yaml (oder wie auch immer Ihre Hauptkonfigurationsdatei heißt)
substitutions:
  name: "wz-display"
  friendly_name: "Wohnzimmer Display"
  room: "Wohnzimmer"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/smogaone/esphome-lvgl/ # Ihr Pfad zu den Paketdateien
    files:
      - device/esp32-s3-touch-lcd-7.yaml
      - addon/time.yaml
      - addon/backlight.yaml
      - addon/network.yaml
      - assets/fonts.yaml
      - assets/icons.yaml
      - assets/images.yaml
      - theme/button.yaml
      - office/sensors.yaml
      - office/lvgl.yaml
    refresh: 1sec
