globals:
  - id: innen_temp_wert
    type: float
    initial_value: '0.0'
  - id: aussen_temp_wert
    type: float
    initial_value: '0.0'

sensor:
  # Innentemperatur (Wohnzimmer)
  - platform: homeassistant
    entity_id: sensor.environment_sensor_temperature_sensor
    id: wz_temperature
    on_value:
      then:
        - lambda: |-
            id(innen_temp_wert) = x;
        - script.execute: update_temperatur_anzeige

  # Außentemperatur
  - platform: homeassistant
    entity_id: sensor.aussentemperatur
    id: outdoor_temperature
    on_value:
      then:
        - lambda: |-
            id(aussen_temp_wert) = x;
        - script.execute: update_temperatur_anzeige


binary_sensor:

  # Office Evening Scene
  - platform: homeassistant
    id: office_scene_evening
    entity_id: binary_sensor.office_scene_evening
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda return x;

  # Office Dimmed Scene
  - platform: homeassistant
    id: office_scene_dimmed
    entity_id: binary_sensor.office_scene_dimmed
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_dimmed_button
          state:
            checked: !lambda return x;

  # Office Calls Scene
  - platform: homeassistant
    id: office_scene_desk_call
    entity_id: binary_sensor.office_scene_desk_call
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_calls_button
          state:
            checked: !lambda return x;

  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features
    entity_id: binary_sensor.office_scene_features
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  # 3d Printer
  - platform: homeassistant
    id: office_3d_printer_power
    entity_id: switch.office_3d_printer_power
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: printer_power_button
          state:
            checked: !lambda return x;

  # Office Aircon
  - platform: homeassistant
    id: wz_lichtschalter
    entity_id: light.wz_lichtschalter
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: wz_button
          state:
            checked: !lambda return x;
