# sensors.yaml
globals:
  - id: innen_temp_wert
    type: float
    initial_value: '0.0'
  - id: aussen_temp_wert
    type: float
    initial_value: '0.0'
  - id: flur_temp_wert
    type: float
    initial_value: '0.0'
  - id: flur_humidity_wert
    type: float
    initial_value: '0.0'

sensor:
  - platform: homeassistant
    entity_id: sensor.environment_sensor_temperature_sensor
    id: wz_temperature
    on_value:
      then:
        - lambda: |-
            id(innen_temp_wert) = x;
        - script.execute: update_temperatur_anzeige
  - platform: homeassistant
    entity_id: sensor.aussentemperatur
    id: outdoor_temperature
    on_value:
      then:
        - lambda: |-
            id(aussen_temp_wert) = x;
        - script.execute: update_temperatur_anzeige
  - platform: homeassistant
    entity_id: sensor.flur_temperatur_temperature
    id: flur_temperature_sensor
    on_value:
      then:
        - lambda: |-
            id(flur_temp_wert) = x;
        - script.execute: update_temperatur_anzeige
  - platform: homeassistant
    entity_id: sensor.flur_temperatur_humidity
    id: flur_humidity_sensor
    on_value:
      then:
        - lambda: |-
            id(flur_humidity_wert) = x;
        - script.execute: update_temperatur_anzeige
  - platform: wifi_signal
    name: "Wifi Signal Strength Icon"
    id: wifi_signal_sensor
    update_interval: 15s
    entity_category: "diagnostic"
    internal: true
    on_value:
      then:
        - script.execute: update_wifi_icon_display

text_sensor:
  - platform: homeassistant
    id: cover_wohnzimmer_links_state_tracker
    entity_id: cover.wohnzimmer_links
    internal: true
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x == "open";'
            then:
              - lvgl.widget.update:
                  id: wz_blind_open_button
                  state:
                    checked: true
              - lvgl.widget.update:
                  id: wz_blind_close_button
                  state:
                    checked: false
        - if:
            condition:
              lambda: 'return x == "closed";'
            then:
              - lvgl.widget.update:
                  id: wz_blind_open_button
                  state:
                    checked: false
              - lvgl.widget.update:
                  id: wz_blind_close_button
                  state:
                    checked: true
        - if:
            condition:
              lambda: 'return x == "opening";'
            then:
              - lvgl.widget.update:
                  id: wz_blind_open_button
                  state:
                    checked: true
              - lvgl.widget.update:
                  id: wz_blind_close_button
                  state:
                    checked: false
        - if:
            condition:
              lambda: 'return x == "closing";'
            then:
              - lvgl.widget.update:
                  id: wz_blind_open_button
                  state:
                    checked: false
              - lvgl.widget.update:
                  id: wz_blind_close_button
                  state:
                    checked: true
        - if:
            condition:
              lambda: 'return x != "open" && x != "closed" && x != "opening" && x != "closing";'
            then:
              - lvgl.widget.update:
                  id: wz_blind_open_button
                  state:
                    checked: false
              - lvgl.widget.update:
                  id: wz_blind_close_button
                  state:
                    checked: false
  - platform: homeassistant
    id: esphome_wetter_png_icon_id
    entity_id: sensor.wetter_icon
    internal: true
    on_value:
      then:
        - if:
            condition:
              lambda: return x == "icon_png_clear_night";
            then:
              - lvgl.image.update:
                  id: lvgl_weather_image_widget
                  src: icon_png_clear_night
            else:
              - if:
                  condition:
                    lambda: return x == "icon_png_cloudy";
                  then:
                    - lvgl.image.update:
                        id: lvgl_weather_image_widget
                        src: icon_png_cloudy
                  else:
                    - if:
                        condition:
                          lambda: return x == "icon_png_exceptional";
                        then:
                          - lvgl.image.update:
                              id: lvgl_weather_image_widget
                              src: icon_png_exceptional
                        else:
                          - if:
                              condition:
                                lambda: return x == "icon_png_fog";
                              then:
                                - lvgl.image.update:
                                    id: lvgl_weather_image_widget
                                    src: icon_png_fog
                              else:
                                - if:
                                    condition:
                                      lambda: return x == "icon_png_hail";
                                    then:
                                      - lvgl.image.update:
                                          id: lvgl_weather_image_widget
                                          src: icon_png_hail
                                    else:
                                      - if:
                                          condition:
                                            lambda: return x == "icon_png_lightning";
                                          then:
                                            - lvgl.image.update:
                                                id: lvgl_weather_image_widget
                                                src: icon_png_lightning
                                          else:
                                            - if:
                                                condition:
                                                  lambda: return x == "icon_png_lightning_rainy";
                                                then:
                                                  - lvgl.image.update:
                                                      id: lvgl_weather_image_widget
                                                      src: icon_png_lightning_rainy
                                                else:
                                                  - if:
                                                      condition:
                                                        lambda: return x == "icon_png_partlycloudy";
                                                      then:
                                                        - lvgl.image.update:
                                                            id: lvgl_weather_image_widget
                                                            src: icon_png_partlycloudy
                                                      else:
                                                        - if:
                                                            condition:
                                                              lambda: return x == "icon_png_pouring";
                                                            then:
                                                              - lvgl.image.update:
                                                                  id: lvgl_weather_image_widget
                                                                  src: icon_png_pouring
                                                            else:
                                                              - if:
                                                                  condition:
                                                                    lambda: return x == "icon_png_rainy";
                                                                  then:
                                                                    - lvgl.image.update:
                                                                        id: lvgl_weather_image_widget
                                                                        src: icon_png_rainy
                                                                  else:
                                                                    - if:
                                                                        condition:
                                                                          lambda: return x == "icon_png_snowy";
                                                                        then:
                                                                          - lvgl.image.update:
                                                                              id: lvgl_weather_image_widget
                                                                              src: icon_png_snowy
                                                                        else:
                                                                          - if:
                                                                              condition:
                                                                                lambda: return x == "icon_png_snowy_rainy";
                                                                              then:
                                                                                - lvgl.image.update:
                                                                                    id: lvgl_weather_image_widget
                                                                                    src: icon_png_snowy_rainy
                                                                              else:
                                                                                - if:
                                                                                    condition:
                                                                                      lambda: return x == "icon_png_sunny";
                                                                                    then:
                                                                                      - lvgl.image.update:
                                                                                          id: lvgl_weather_image_widget
                                                                                          src: icon_png_sunny
                                                                                    else:
                                                                                      - if:
                                                                                          condition:
                                                                                            lambda: return x == "icon_png_windy";
                                                                                          then:
                                                                                            - lvgl.image.update:
                                                                                                id: lvgl_weather_image_widget
                                                                                                src: icon_png_windy
                                                                                          else:
                                                                                            - if:
                                                                                                condition:
                                                                                                  lambda: return x == "icon_png_windy_variant";
                                                                                                then:
                                                                                                  - lvgl.image.update:
                                                                                                      id: lvgl_weather_image_widget
                                                                                                      src: icon_png_windy_variant
  - platform: homeassistant
    id: esphome_weather_forecast_home
    entity_id: sensor.wetter_deutsch
    internal: true
    on_value:
      then:
        - if:
            condition:
              lambda: return !x.empty();
            then:
              - lvgl.label.update:
                  id: weather_description
                  text: !lambda return x.c_str();
  - platform: homeassistant
    id: apple_tv_media_title_sensor
    entity_id: media_player.wohnzimmer_apple_tv
    attribute: media_title
    internal: true
    on_value:
      - lvgl.label.update:
          id: main_page_media_title
          text: !lambda 'return x.empty() ? "Apple TV" : x;'
  - platform: homeassistant
    id: apple_tv_media_artist_sensor
    entity_id: media_player.wohnzimmer_apple_tv
    attribute: media_artist
    internal: true
    on_value:
      - lvgl.label.update:
          id: main_page_media_artist
          text: !lambda 'return x.empty() ? "Standby" : x;'
  - platform: homeassistant
    id: apple_tv_media_image_url_sensor
    entity_id: media_player.wohnzimmer_apple_tv
    attribute: entity_picture
    internal: true
    on_value:
      - if:
          condition:
            lambda: 'return x.length() > 0;'
          then:
            - online_image.set_url:
                id: album_art_online_image
                url: !lambda 'return "http://192.168.178.122:8123" + x;'
            - lvgl.image.update:
                id: main_page_media_image
                src: album_art_online_image
          else:
            - lvgl.image.update:
                id: main_page_media_image
                src: apple_tv_logo_png
  - platform: homeassistant
    id: apple_tv_state_sensor
    entity_id: media_player.wohnzimmer_apple_tv
    internal: true
    on_value:
      - if:
          condition:
            lambda: 'return x == "playing" || x == "on";'
          then:
            - lvgl.label.update:
                id: main_page_media_play_pause_icon
                text: $pause
            - lvgl.widget.update:
                id: main_page_media_container
                bg_color: $button_on_color
          else:
            - lvgl.label.update:
                id: main_page_media_play_pause_icon
                text: $play
            - lvgl.widget.update:
                id: main_page_media_container
                bg_color: $button_control_color

binary_sensor:
  - platform: homeassistant
    id: wohnzimmer_deckenlampe_status
    entity_id
